In [12]:
import os
import pandas as pd
import numpy as np
# Show all columns
pd.set_option('display.max_columns', None)
import warnings
import seaborn as sns
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

In [2]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

## Download image data using provided download CLI
Below we download all metadata and resized images (500p) for a FungiTastic-Mini subset.

In [3]:
# !python ../../dataset/download.py --metadata --images --subset "m" --size "500" --save_path "./"

In [4]:
!ls ./FungiTastic/metadata/FungiTastic-Mini/

FungiTastic-Mini-ClosedSet-Test.csv FungiTastic-Mini-OpenSet-Test.csv
FungiTastic-Mini-ClosedSet-Val.csv  FungiTastic-Mini-OpenSet-Val.csv
FungiTastic-Mini-DNA-Test.csv       FungiTastic-Mini-Train.csv

In [5]:
!ls ./FungiTastic/FungiTastic-Mini

dna-test test     train    val

## Load and preprocess metadata

In [174]:
print(os.getcwd())

/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/baselines/closed_set

In [216]:
BASE_METADATA_PATH = f"{os.getcwd()}/FungiTastic/metadata/FungiTastic-Mini/"

train_df = pd.read_csv(f"{BASE_METADATA_PATH}FungiTastic-Mini-Train.csv")
val_df = pd.read_csv(f"{BASE_METADATA_PATH}FungiTastic-Mini-ClosedSet-Val.csv")
test_df = pd.read_csv(f"{BASE_METADATA_PATH}FungiTastic-Mini-ClosedSet-Test.csv")

### Setting image_path to the images.

In [217]:
BASE_IMAGE_PATH = "./FungiTastic/FungiTastic-Mini"
SIZE = "500p"

train_df["image_path"] = train_df.filename.apply(lambda filename: f"{BASE_IMAGE_PATH}/train/{SIZE}/{filename}")
val_df["image_path"] = val_df.filename.apply(lambda filename: f"{BASE_IMAGE_PATH}/val/{SIZE}/{filename}")

In [218]:
print("Shape of train_df: ", train_df.shape)
print("Shape of val_df: ", val_df.shape)

Shape of train_df:  (46842, 32)
Shape of val_df:  (9412, 32)

## Remove Taxonomic Features

In [219]:
train_df = train_df[['species', 'year', 'month', 'day', 'habitat', 'countryCode','hasCoordinate','iucnRedListCategory','substrate','latitude','longitude','coorUncert','region','district','metaSubstrate','poisonous','elevation','landcover','biogeographicalRegion']]

In [220]:
val_df = val_df[['species', 'year', 'month', 'day', 'habitat', 'countryCode','hasCoordinate','iucnRedListCategory','substrate','latitude','longitude','coorUncert','region','district','metaSubstrate','poisonous','elevation','landcover','biogeographicalRegion']]

## Analyze number of nan rows and drop them

In [221]:
train_df_num_nan_rows = train_df.isna().any(axis=1).sum()
print("train_df number of nan rows: ", train_df_num_nan_rows)

val_df_num_nan_rows = val_df.isna().any(axis=1).sum()
print("val_df number of nan rows: ", val_df_num_nan_rows)

print("Percentage nan rows train_df: ", train_df_num_nan_rows / train_df.shape[0])
print("Percentage nan rows val_df: ", val_df_num_nan_rows / val_df.shape[0])

train_df number of nan rows:  2414
val_df number of nan rows:  21
Percentage nan rows train_df:  0.051534947269544426
Percentage nan rows val_df:  0.0022311942201444965

In [222]:
train_df.dropna(inplace=True)
val_df.dropna(inplace=True)

In [223]:
print("Shape of train_df after dropping nan rows: ", train_df.shape)
print("Shape of val_df after dropping nan rows: ", val_df.shape)

Shape of train_df after dropping nan rows:  (44428, 19)
Shape of val_df after dropping nan rows:  (9391, 19)

In [224]:
train_df.columns

Index(['species', 'year', 'month', 'day', 'habitat', 'countryCode',
       'hasCoordinate', 'iucnRedListCategory', 'substrate', 'latitude',
       'longitude', 'coorUncert', 'region', 'district', 'metaSubstrate',
       'poisonous', 'elevation', 'landcover', 'biogeographicalRegion'],
      dtype='object')

## Analyze distribution of labels and narrow to most frequent N

In [225]:
train_species_count = train_df['species'].value_counts()

train_proportions = train_df['species'].value_counts(normalize=True)
summary = pd.DataFrame({
    'Count': train_species_count,
    'Proportion': train_proportions,
})
summary.describe()

             Count  Proportion
count   210.000000  210.000000
mean    211.561905    0.004762
std     266.743302    0.006004
min       5.000000    0.000113
25%      50.250000    0.001131
50%     105.500000    0.002375
75%     267.750000    0.006027
max    1745.000000    0.039277

In [226]:
print(max(train_species_count.values))
print(min(train_species_count.values))

1745
5

In [227]:
train_df_count_quantiles = train_df["species"].value_counts().quantile([0.25, 0.5, 0.75])
train_df_count_quantiles

0.25     50.25
0.50    105.50
0.75    267.75
Name: count, dtype: float64

In [228]:
min_samples = 150  # or whatever makes sense for your model
valid_classes = (train_species_count[train_species_count >= min_samples])
N = len(valid_classes)
print(N)
print(len(train_species_count))
print(N / len(train_species_count))

89
210
0.4238095238095238

In [229]:
print(sum(list(dict(train_species_count).values())[:N]))

sum_of_top_n_labels = sum(list(dict(train_species_count).values())[:N])
print(sum_of_top_n_labels / train_df.shape[0])

36958
0.8318627892320158

In [230]:
min_200_labels = list(dict(valid_classes).keys())

In [231]:
train_df = train_df[train_df['species'].isin(min_200_labels)]
val_df = val_df[val_df['species'].isin(min_200_labels)]

print("Shape of train_df: ", train_df.shape)
print("Shape of val_df: ", val_df.shape)

Shape of train_df:  (36958, 19)
Shape of val_df:  (8193, 19)

## Split Train into Train and Test
- Because the test df that came from FungiTastic doesn't have labels, we will split the train into train and test.

In [232]:
from sklearn.model_selection import train_test_split

In [233]:
X = train_df[list(set(train_df.columns) - set(['species']))]
Y = train_df['species']

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=1234, stratify=Y
)

X_val = val_df[list(set(val_df.columns) - set(['species']))]
Y_val = val_df['species']

In [235]:
print("Shape of X_train: ", X_train.shape)
print("Shape of Y_train: ", Y_train.shape)

print("Shape of X_test: ", X_test.shape)
print("Shape of Y_test: ", Y_test.shape)

print("Shape of X_val: ", X_val.shape)
print("Shape of Y_val: ", Y_val.shape)

Shape of X_train:  (29566, 18)
Shape of Y_train:  (29566,)
Shape of X_test:  (7392, 18)
Shape of Y_test:  (7392,)
Shape of X_val:  (8193, 18)
Shape of Y_val:  (8193,)

In [83]:
train_df_num_nan_rows = train_df.isna().any(axis=1).sum()
print(train_df_num_nan_rows)

test_df_num_nan_rows = test_df.isna().any(axis=1).sum()
print(test_df_num_nan_rows)

val_df_num_nan_rows = val_df.isna().any(axis=1).sum()
print(val_df_num_nan_rows)

print("Percentage nan rows train_df: ", train_df_num_nan_rows / train_df.shape[0])
print("Percentage nan rows test_df: ", test_df_num_nan_rows / test_df.shape[0])
print("Percentage nan rows val_df: ", val_df_num_nan_rows / val_df.shape[0])

2414
19
21
Percentage nan rows train_df:  0.051534947269544426
Percentage nan rows test_df:  0.0017694170236543117
Percentage nan rows val_df:  0.0022311942201444965

In [95]:
train_df.dropna(inplace=True)
test_df.dropna(inplace=True)
val_df.dropna(inplace=True)

### Preprocess Metadata

'species', 'year', 'month', 'day', 'habitat', 'countryCode',
       'hasCoordinate', 'iucnRedListCategory', 'substrate', 'latitude',
       'longitude', 'coorUncert', 'region', 'district', 'metaSubstrate',
       'poisonous', 'elevation', 'landcover', 'biogeographicalRegion'

In [212]:
train_df.columns

Index(['species', 'year', 'month', 'day', 'habitat', 'countryCode',
       'hasCoordinate', 'iucnRedListCategory', 'substrate', 'latitude',
       'longitude', 'coorUncert', 'region', 'district', 'metaSubstrate',
       'poisonous', 'elevation', 'landcover', 'biogeographicalRegion'],
      dtype='object')

In [ ]:
metadata_feat_list = [
    'year', 'month', 'day', 'habitat', 'countryCode',
       'hasCoordinate', 'iucnRedListCategory', 'substrate', 'latitude',
       'longitude', 'coorUncert', 'region', 'district', 'metaSubstrate',
       'poisonous', 'elevation', 'landcover', 'biogeographicalRegion'
]
train_df_metadata = train_df[metadata_feat_list]
val_df_metadata = val_df[metadata_feat_list]
# test_df_metadata = test_df[metadata_feat_list]

In [213]:
train_df.describe()

,year,month,day,latitude,longitude,coorUncert,poisonous,elevation,landcover
count,34018.000000,34018.000000,34018.000000,34018.000000,34018.000000,34018.000000,34018.000000,34018.000000,34018.000000
mean,2018.481363,8.927156,16.221383,55.763982,11.031970,68.309130,0.158681,67.737382,11.610059
std,3.121157,1.791852,8.820333,0.840140,1.595129,332.336381,0.365383,140.909246,5.512024
min,1982.000000,1.000000,1.000000,39.096246,-9.261015,1.000000,0.000000,0.000000,1.000000
25%,2018.000000,8.000000,9.000000,55.372245,9.826906,10.000000,0.000000,0.000000,8.000000
50%,2019.000000,9.000000,16.000000,55.780202,10.991928,25.000000,0.000000,13.000000,12.000000
75%,2021.000000,10.000000,24.000000,56.091846,12.284655,50.000000,0.000000,71.000000,17.000000
max,2021.000000,12.000000,31.000000,69.706248,29.473609,24069.000000,1.000000,2313.000000,17.000000

### Frequency Encoding

In [101]:
cat_metadata_feat_list = [
    'habitat', 'countryCode',
    'scientificName', 'kingdom', 'phylum', 'class', 'order', 'family',
    'genus', 'specificEpithet', 'hasCoordinate',
    'iucnRedListCategory', 'substrate', 'coorUncert', 'region', 'district', 
    'metaSubstrate', 'biogeographicalRegion'
]

cat_train_df_metadata = train_df_metadata[cat_metadata_feat_list]
cat_val_df_metadata = val_df_metadata[cat_metadata_feat_list]

In [102]:
train_cat_vc_dict = {}
val_cat_vc_dict = {}

for cat in list(cat_train_df_metadata.columns):
    
    train_cat_vc_dict[cat] = dict(cat_train_df_metadata[cat].value_counts())
    val_cat_vc_dict[cat] = dict(cat_val_df_metadata[cat].value_counts())

In [103]:
train_df_metadata_cat_enc = train_df_metadata.copy()

In [104]:
for col, mapping in train_cat_vc_dict.items():
    # Use .map with dict (fast, vectorized, memory-friendly)
    train_df_metadata_cat_enc[col] = train_df_metadata[col].map(mapping)

In [105]:
val_df_metadata_cat_enc = val_df_metadata.copy()

In [106]:
for col, mapping in val_cat_vc_dict.items():
    # Use .map with dict (fast, vectorized, memory-friendly)
    val_df_metadata_cat_enc[col] = val_df_metadata[col].map(mapping)

In [107]:
val_df_metadata_cat_enc.isna().sum().sum()

np.int64(0)

### Coordinates Parsing

In [108]:
train_df_metadata_cat_enc["lat_sin"] = np.sin(np.radians(train_df_metadata_cat_enc["latitude"]))
train_df_metadata_cat_enc["lat_cos"] = np.cos(np.radians(train_df_metadata_cat_enc["latitude"]))
train_df_metadata_cat_enc["lon_sin"] = np.sin(np.radians(train_df_metadata_cat_enc["longitude"]))
train_df_metadata_cat_enc["lon_cos"] = np.cos(np.radians(train_df_metadata_cat_enc["longitude"]))

In [109]:
val_df_metadata_cat_enc["lat_sin"] = np.sin(np.radians(val_df_metadata_cat_enc["latitude"]))
val_df_metadata_cat_enc["lat_cos"] = np.cos(np.radians(val_df_metadata_cat_enc["latitude"]))
val_df_metadata_cat_enc["lon_sin"] = np.sin(np.radians(val_df_metadata_cat_enc["longitude"]))
val_df_metadata_cat_enc["lon_cos"] = np.cos(np.radians(val_df_metadata_cat_enc["longitude"]))

### Target Label encoding

In [110]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
train_df_target_enc = le.fit_transform(train_target)
val_df_target_enc = le.transform(val_target)

In [111]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
train_arr_metadata_cat_enc = std_scaler.fit_transform(train_df_metadata_cat_enc)
val_arr_metadata_cat_enc = std_scaler.transform(val_df_metadata_cat_enc)

In [112]:
train_df_metadata_cat_enc.columns

Index(['habitat', 'countryCode', 'scientificName', 'kingdom', 'phylum',
       'class', 'order', 'family', 'genus', 'specificEpithet', 'hasCoordinate',
       'iucnRedListCategory', 'substrate', 'latitude', 'longitude',
       'coorUncert', 'region', 'district', 'metaSubstrate', 'poisonous',
       'elevation', 'landcover', 'biogeographicalRegion', 'lat_sin', 'lat_cos',
       'lon_sin', 'lon_cos'],
      dtype='object')

### Preprocess Images

In [113]:
import tensorflow as tf

In [114]:
print(os.getcwd())

/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/baselines/closed_set

In [115]:
def load_and_preprocess_image(path):
    image = tf.io.read_file(path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [224, 224])  # consistent input shape
    image = image / 255.0                       # normalize [0,1]
    return image

In [116]:
def process_row(path, metadata, label):
    image = load_and_preprocess_image(path)
    return ({"image": image, "metadata": metadata}, label)

In [117]:
def standardize_image(inputs, label, mean, std):
    image = inputs["image"]
    metadata = inputs["metadata"]
    image = (tf.cast(image, tf.float32) - mean) / std
    return {"image": image, "metadata": metadata}, label

In [118]:
def standardize_image_v2(inputs, label, mean, std):
    image = inputs["image"]
    metadata = inputs["metadata"]

    # Works whether image is 3D or 4D
    image = tf.cast(image, tf.float32)
    mean = tf.reshape(mean, [1, 1, 1, 3])
    std = tf.reshape(std, [1, 1, 1, 3])
    image = (image - mean) / std

    return {"image": image, "metadata": metadata}, label

### Train set image processing

In [119]:
train_df_target_enc.shape

(44428,)

In [120]:
type(train_df_metadata_cat_enc)

pandas.core.frame.DataFrame

In [121]:
train_df.shape

(44428, 32)

In [ ]:
train_image_paths = train_df['image_path'].astype(str)
train_labels = tf.stack(train_df_target_enc.tolist())

# Build dataset from (image_paths, metadata_features, labels)
train_dataset = tf.data.Dataset.from_tensor_slices((train_image_paths, train_df_metadata_cat_enc, train_labels))
# train_dataset = np.hstack([train_image_paths, train_df_metadata_cat_enc, train_labels])

train_dataset = train_dataset.map(process_row, num_parallel_calls=tf.data.AUTOTUNE)
train_dataset = train_dataset.shuffle(1000).prefetch(tf.data.AUTOTUNE)

In [122]:
train_image_paths = pd.DataFrame(train_df['image_path'].astype(str))
train_labels = np.array(train_df_target_enc)
train_metadata = np.array(train_df_metadata_cat_enc)

train_dataset_images = train_image_paths.map(load_and_preprocess_image).to_numpy()
# train_dataset = train_dataset.shuffle(1000).prefetch(tf.data.AUTOTUNE)

:

In [82]:
type(train_dataset_images)

numpy.ndarray

In [83]:
type(train_labels)

numpy.ndarray

In [84]:
type(train_metadata)

numpy.ndarray

In [86]:
train_dataset_dict = {'images': train_dataset_images, 'metadata': train_metadata}

In [51]:
# Initialize accumulators
num_pixels = 0
sum_pixels = tf.zeros([3], dtype=tf.float32)
sum_squared_pixels = tf.zeros([3], dtype=tf.float32)

for element in train_dataset.unbatch():
    # element is ((dict_of_inputs), label)
    inputs, label = element
    image = inputs["image"]          # extract the image tensor
    image = tf.cast(image, tf.float32)
    
    # accumulate sums per channel
    sum_pixels += tf.reduce_sum(image, axis=[0, 1])
    sum_squared_pixels += tf.reduce_sum(tf.square(image), axis=[0, 1])
    num_pixels += image.shape[0] * image.shape[1]

# compute mean and std per channel
mean = sum_pixels / num_pixels
std = tf.sqrt(sum_squared_pixels / num_pixels - tf.square(mean))

print("Dataset mean per channel:", mean.numpy())
print("Dataset std per channel:", std.numpy())

ValueError: Cannot unbatch an input with scalar components.

In [115]:
train_dataset_standardized = train_dataset.map(
    lambda inputs, label: standardize_image(inputs, label, mean, std),
    num_parallel_calls=tf.data.AUTOTUNE
)
train_dataset_standardized = train_dataset_standardized.shuffle(1000).prefetch(tf.data.AUTOTUNE)

### Validation set image processing

In [103]:
val_image_paths = val_df['image_path'].astype(str).values
val_labels = tf.stack(val_df_target_enc.tolist())

# Build dataset from (image_paths, metadata_features, labels)
val_dataset = tf.data.Dataset.from_tensor_slices((val_image_paths, val_df_metadata_cat_enc, val_labels))

val_dataset = val_dataset.map(process_row, num_parallel_calls=tf.data.AUTOTUNE)
val_dataset = val_dataset.shuffle(1000).prefetch(tf.data.AUTOTUNE)

In [116]:
val_dataset_standardized = val_dataset.map(
    lambda inputs, label: standardize_image(inputs, label, mean, std),
    num_parallel_calls=tf.data.AUTOTUNE
)
val_dataset_standardized = val_dataset_standardized.shuffle(1000).prefetch(tf.data.AUTOTUNE)

In [89]:
from keras import layers, models

images = []
metadata = []
labels = []

for features, label in train_dataset:
    images.append(features['image'].numpy())
    metadata.append(features['metadata'].numpy())
    labels.append(label.numpy())

# Convert to NumPy arrays
images = np.stack(images)
metadata = np.stack(metadata)
labels = np.array(labels)

In [90]:
# Image branch
image_input = layers.Input(shape=(224, 224, 3), name="images")
x = layers.Conv2D(32, (3, 3), activation="relu")(image_input)
x = layers.MaxPooling2D()(x)
x = layers.Flatten()(x)

# Metadata branch
metadata_input = layers.Input(shape=(train_df_metadata_cat_enc.shape[1],), name="metadata")
y = layers.Dense(32, activation="relu")(metadata_input)

# Combine both
combined = layers.concatenate([x, y])
z = layers.Dense(64, activation="relu")(combined)
output = layers.Dense(len(le.classes_), activation="softmax")(z)

model = models.Model(inputs=[image_input, metadata_input], outputs=output)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [91]:
model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ images (InputLayer) │ (None, 224, 224,  │          0 │ -                 │
│                     │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 222, 222,  │        896 │ images[0][0]      │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_1     │ (None, 111, 111,  │          0 │ conv2d_1[0][0]    │
│ (MaxPooling2D)      │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ metadata            │ (None, 27)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_1 (Flatten) │ (None, 394272)    │          0 │ max_pooling2d_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 32)        │        896 │ metadata[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_1       │ (None, 394304)    │          0 │ flatten_1[0][0],  │
│ (Concatenate)       │                   │            │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 64)        │ 25,235,520 │ concatenate_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 210)       │     13,650 │ dense_4[0][0]     │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 25,250,962 (96.32 MB)

 Trainable params: 25,250,962 (96.32 MB)

 Non-trainable params: 0 (0.00 B)

In [92]:
train_dataset_dict['images'].shape

(10, 1)

In [62]:
train_dataset_dict['metadata'].shape

(10, 27)

In [64]:
history = model.fit(
    x=train_dataset_dict,
    y=labels,
    epochs=10,
    # validation_data=val_dataset_standardized,  # if you have a validation dataset
    batch_size=32
)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.0000e+00 - loss: 474.7303
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.0000e+00 - loss: 69.7512
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7000 - loss: 58.4634
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.7000 - loss: 33.7964
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.7000 - loss: 17.8862
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.0000e+00

## Logistic Regression on Encoded Metadata

In [228]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

clf_logreg_ovr = OneVsRestClassifier(LogisticRegression(max_iter=1000))
clf_logreg_ovr.fit(train_arr_metadata_cat_enc, train_df_target_enc)  # Y is binarized labels from MultiLabelBinarizer

OneVsRestClassifier(estimator=LogisticRegression(max_iter=1000))

In [231]:
# Predict on validation data
Y_pred_logreg_ovr = clf_logreg_ovr.predict(val_arr_metadata_cat_enc)

In [232]:
Y_pred_logreg_ovr

array([44, 44, 44, ..., 44, 23, 45], shape=(9391,))

In [233]:
val_df_target_enc

array([71, 60, 60, ..., 86, 32, 43], shape=(9391,))

In [234]:
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(val_df_target_enc, Y_pred_logreg_ovr))

Accuracy: 0.020338622084974976

### Update the column name to fit the FGVC expected naming convention and save the updated metadata

In [10]:
!mkdir metadata

train_df = train_df.rename(columns={"category_id":"class_id"})
val_df = val_df.rename(columns={"category_id":"class_id"})

train_df.to_csv("./metadata/FungiTastic-Mini-Train.csv", index=None)
val_df.to_csv("./metadata/FungiTastic-Mini-ClosedSet-Val.csv", index=None)

mkdir: metadata: File exists

## Train single model with a config file.

### Environment variables
Select which GPU to use and add your WANDB_ENTITY and WANDB_PROJECT you want to log into etc.

In [11]:
%env CUDA_DEVICES = 0
%env WANDB_ENTITY = zcu_cv
%env HFHUB_OWNER = BVRA
%env WANDB_PROJECT = FungiTastic
%env TRAIN_METADATA_PATH = ./metadata/FungiTastic-Mini-Train.csv
%env VAL_METADATA_PATH = ./metadata/FungiTastic-Mini-ClosedSet-Val.csv
%env TEST_METADATA_PATH = ./metadata/FungiTastic-Mini-ClosedSet-Test.csv

os.environ["CUDA_VISIBLE_DEVICES"] = os.environ["CUDA_DEVICES"]

env: CUDA_DEVICES=0
env: WANDB_ENTITY=zcu_cv
env: HFHUB_OWNER=BVRA
env: WANDB_PROJECT=FungiTastic
env: TRAIN_METADATA_PATH=./metadata/FungiTastic-Mini-Train.csv
env: VAL_METADATA_PATH=./metadata/FungiTastic-Mini-ClosedSet-Val.csv
env: TEST_METADATA_PATH=./metadata/FungiTastic-Mini-ClosedSet-Test.csv

In [14]:
!which python
!python -m pip install wandb

/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/bin/python
Collecting wandb
  Using cached wandb-0.22.0-py3-none-macosx_12_0_arm64.whl.metadata (10 kB)
Collecting click>=8.0.1 (from wandb)
  Using cached click-8.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting gitpython!=3.1.29,>=1.0.0 (from wandb)
  Using cached gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (25.0)
Requirement already satisfied: platformdirs in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (4.4.0)
Collecting protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 (from wandb)
  Using cached protobuf-6.32.1-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Requirement already satisfied: pydantic<3 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (2.11.9)
Requirement already satisfied: pyyaml in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (6.0.2)
Requirement already satisfied: requests<3,>=2.0.0 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (2.32.5)
Collecting sentry-sdk>=2.0.0 (from wandb)
  Downloading sentry_sdk-2.39.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: typing-extensions<5,>=4.8 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from wandb) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from pydantic<3->wandb) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages (from requests<3,>=2.0.0->wandb) (2025.8.3)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Using cached wandb-0.22.0-py3-none-macosx_12_0_arm64.whl (18.3 MB)
Using cached protobuf-6.32.1-cp39-abi3-macosx_10_9_universal2.whl (426 kB)
Using cached click-8.3.0-py3-none-any.whl (107 kB)
Using cached gitpython-3.1.45-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading sentry_sdk-2.39.0-py2.py3-none-any.whl (370 kB)
Installing collected packages: smmap, sentry-sdk, protobuf, click, gitdb, gitpython, wandb
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [wandb]32m6/7 [wandb]uf]k]
Successfully installed click-8.3.0 gitdb-4.0.12 gitpython-3.1.45 protobuf-6.32.1 sentry-sdk-2.39.0 smmap-5.0.2 wandb-0.22.0

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [16]:
!python train.py \
    --train-path "./metadata/FungiTastic-Mini-Train.csv" \
    --val-path "./metadata/FungiTastic-Mini-ClosedSet-Val.csv" \
    --test-path "./metadata/FungiTastic-Mini-ClosedSet-Test.csv" \
    --config-path ./configs/default_config.yaml \
    --cuda-devices $CUDA_DEVICES \
    --wandb-entity $WANDB_ENTITY \
    --wandb-project $WANDB_PROJECT \
    --hfhub-owner $HFHUB_OWNER

(script) INFO: Loading training config.
(script) DEBUG: Extra arguments passed to the script: {}
(script) INFO: Setting run name: resnet18.a1_in1k-CrossEntropyLoss-light
(script) INFO: Using experiment directory: ../runs/resnet18.a1_in1k-CrossEntropyLoss-light/exp2
(script) INFO: Using training configuration: {
    "augmentations": "light",
    "image_size": [
        224,
        224
    ],
    "dataset": "FungiTastic-Mini",
    "architecture": "resnet18.a1_in1k",
    "train": null,
    "loss": "CrossEntropyLoss",
    "optimizer": "SGD",
    "scheduler": "plateau",
    "epochs": 1,
    "learning_rate": 0.01,
    "batch_size": 64,
    "accumulation_steps": 1,
    "random_seed": 777,
    "workers": 8,
    "multigpu": false,
    "tags": [
        "FungiTastic-M-CloseSet",
        "224x224",
        "Convolutional"
    ],
    "root_path": "../",
    "run_name": "resnet18.a1_in1k-CrossEntropyLoss-light",
    "exp_name": "exp2",
    "exp_path": "../runs/resnet18.a1_in1k-CrossEntropyLoss-light/exp2"
}
(fgvc) INFO: Using device: cpu (0)
(fgvc) INFO: Device names:
(script) INFO: Loading training and validation metadata.
(script) INFO: Loaded training metadata. Number of samples: 46842
(script) INFO: Loaded validation metadata. Number of samples: 9412
(script) INFO: Loaded test metadata. Number of samples: 10738
(script) INFO: Creating model, optimizer, and scheduler.
model.safetensors: 100%|███████████████████| 46.8M/46.8M [00:04<00:00, 11.4MB/s]
(fgvc) DEBUG: Setting new prediction head with random initial weights.
Traceback (most recent call last):
  File "/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/baselines/closed_set/train.py", line 414, in <module>
    train_clf()
  File "/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/baselines/closed_set/train.py", line 295, in train_clf
    optimizer, scheduler = get_optimizer_and_scheduler(model, config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages/fgvc/utils/experiment.py", line 480, in get_optimizer_and_scheduler
    scheduler = get_scheduler(
                ^^^^^^^^^^^^^^
  File "/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages/fgvc/core/optimizers.py", line 86, in get_scheduler
    scheduler = reduce_lr_on_plateau(optimizer, *args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremycui/Documents/UCB_MIDS/DATASCI207/fungitastic-classification-datasci207-Fall-2025/.dataset_demo_venv/lib/python3.12/site-packages/fgvc/core/optimizers.py", line 48, in reduce_lr_on_plateau
    return ReduceLROnPlateau(optimizer, "min", factor=0.9, patience=1, verbose=True, eps=1e-6)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ReduceLROnPlateau.__init__() got an unexpected keyword argument 'verbose'

## Running Sweep Training

### Environment variables
Select which GPU to use and add your WANDB_ENTITY and WANDB_PROJECT you want to log into etc.

In [ ]:
%env CUDA_DEVICES = "changethis"
%env WANDB_ENTITY = "changethis"
%env HFHUB_OWNER = "changethis"
%env WANDB_PROJECT = "changethis"
%env TRAIN_METADATA_PATH = ./metadata/FungiTastic-Mini-Train.csv
%env VAL_METADATA_PATH = ./metadata/FungiTastic-Mini-ClosedSet-Val.csv
%env TEST_METADATA_PATH = ./metadata/FungiTastic-Mini-ClosedSet-Test.csv

os.environ["CUDA_VISIBLE_DEVICES"] = os.environ["CUDA_DEVICES"]

In [ ]:
!wandb sweep ./sweep_configs/FungiTastic-M-CloseSet-224.yaml

In [ ]:
!wandb agent <WANDB_ENTITY>/<WANDB_PROJECT>/.....